# Purpose: manual upload of one or more works from Thoth to Internet Archive.
# Work must have a valid URL supplied as the PDF Publication Canonical Location.
# Work must not have previously been uploaded to Internet Archive.
# IA credentials for a user with write permissions to the Thoth Archiving Network
# collection (e.g. thoth_pub) must be present as repository secrets
# named IA_S3_ACCESS (access key) and IA_S3_SECRET (secret key).
# It is advised not to upload until the work is published and all metadata finalised.
name: manual-ia-upload

on:
  workflow_dispatch:
    inputs:
      workIds:
        description: 'Thoth work IDs in array format, e.g. [id1, id2]'
        required: true

env:
  DOCKER_TAG: disseminator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.DOCKER_TAG }}
          outputs: type=docker,dest=/tmp/${{ env.DOCKER_TAG }}.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DOCKER_TAG }}
          path: /tmp/${{ env.DOCKER_TAG }}.tar
          retention-days: 1

  upload_to_ia:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(github.event.inputs.workIds) }}
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DOCKER_TAG }}
          path: /tmp

      - name: Run disseminator using Docker image
        run: |
          docker load --input /tmp/${{ env.DOCKER_TAG }}.tar
          docker run \
            --env ia_s3_access=${{ secrets.IA_S3_ACCESS }} \
            --env ia_s3_secret=${{ secrets.IA_S3_SECRET }} \
            --rm ${{ env.DOCKER_TAG }} \
            ./disseminator.py --work ${{ matrix.work-id }} \
            --platform InternetArchive